webserver:
  root_path: "../develop"
  port: 8000

paths:
  jade:
    src: '../src/templates/*.jade'
    src_shared: '../src/templates/shared/*.jade'
    develop_compile: '../develop'

  stylus:
    base: '../src/assets/stylesheets/*.styl'
    src: '../src/assets/stylesheets/application.styl'
    develop_compile: '../develop/css'

  images:
    sprite:
      src: '../src/assets/images/sprite/*.png'
      develop_compile_images: '../develop/images'
      develop_compile_styles: '../src/assets/stylesheets/'
    static:
      src: '../src/assets/images/**.*'
      develop: '../develop/images/'
