webserver:
  root_path: "../develop"
  port: 8000

paths:
  jade:
    src: '../src/templates/*.jade'
    src_shared: '../src/templates/shared/*.jade'
    develop_compile: '../develop'
    develop_production: '../production'

  sass:
    base: '../src/assets/stylesheets/*.sass'
    src: '../src/assets/stylesheets/application.sass'
    develop_compile: '../develop/css/'
